### ISSUE TITLE
Packagist release

### ISSUE THREAD

**Issue by RoelofRuis** [letyii/yii2-mongo-nested-set#1]
I'm currently using the NestedSetsQueryBehavior to make the Kartik-V Tree Manager work with MongoDB and it works great! 

I however had to copy the classes directly into my codebase because I couldn't find them on packagist. Do you plan on releasing this repository there any time soon?

**Comment by nguago** [comment]
i dont develop it, i just convert kartik-V's class to support mongodb because i need it!

**Comment by nguago** [comment]
https://packagist.org/packages/letyii/yii2-mongo-nested-set

**Comment by RoelofRuis** [comment]
Oh great, thanks for pointing me there! Guess I overlooked it earlier...
